---
title: 'Assignment -2 '
author: "Akash Chauhan"
date: "11/14/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r echo=TRUE}
#It is given that a collection of health-related surveys conducted each year of more than 400,000 Americans, and the Kaiser Family Foundation to show the number of people who are at high risk of becoming seriously ill from COVID-19 per ICU bed in each metropolitan area, metropolitan area or metropolitan division for which we have data.
# Data field info
# 1.MMSA	The name of the metropolitan area, metropolitan area or metropolitan division available in the CDC’s BRFSS
# 2.total_percent_at_risk	The percent of individuals in that area that are at high risk of becoming seriously ill from COVID-19, per CDC’s BRFSS
#3.high_risk_per_ICU_bed	The number of high risk individuals per ICU bed in that area
#4.high_risk_per_hospital	The number of high risk individuals per hospital in that area
#5.ICU_beds	The number of ICU beds in the area, based on the Kaiser Family Foundation’s data
#6.hospitals	The number of hospitals in the area, based on the Kaiser Family Foundation’s data
#7.total_at_risk	The total number of high risk individuals in the area, per CDC’s BRFSS

#Data format : It is a .csv file downloaded from a data source on Github, where the values are separated by delimiter "coma".
```

```{r echo=TRUE}
library(readr)
library(tidyverse)
library(dplyr)

#Creating a variable that has all the content from .csv file
local_file <- "mmsa-icu-beds.csv"
# reading csv data using the read function"
Coviddata <- read_csv(local_file)
# Now,previewing the data loaded from mmsa-icu-beds into R
head(Coviddata)

```


```{r, echo=TRUE}
#performing two data cleaning function as per question
#1. Find the rows with the missing values
#2.Remove the rows with the missing values from the data

# checking for missing values in the data frame
is.na(Coviddata)
# removing missing values from coviddata
Coviddata <- Coviddata[complete.cases(Coviddata), ]
# partial_records <- sampledata[complete.cases(sampledata)]
```


```{r echo =TRUE, include=TRUE}
# For cleaning process,renaming the column names using dplyr
library(dplyr)
# modifying the coloumn names in coviddata and storing 

colnames(Coviddata)<- c("MMSA","percent_at_risk","patient_per_ICU_bed","Patient_per_hospital", "no_icu","no_hospital", "total_at_risk")

head(Coviddata)

```

```{r, echo=TRUE}
# extracting the top 10 rows to subset the row values
Coviddata %>% sample_n(10, replace=FALSE) 

#extracting the top 10 rows to subset the row values
cov <- Coviddata %>% sample_n(10, replace=FALSE) 
print(cov)

#extracting the column values  and concatenating using c and storing in dfcol
dfcol<- Coviddata[,c(1,2,3,4)] 
```


```{r, echo=TRUE, include=TRUE}
#inline code output
```

This dataframe has `r nrow(Coviddata)` rows and `r ncol(Coviddata)` columns. The names of the columns and a brief description of each are in the table below :

```{r, echo=TRUE}
#showing description of each coloumn in a table format
library(knitr)
description <- c('The name of the metropolitan area, metropolitan area or metropolitan division available in the CDC’s BRFSS','	The percent of individuals in that area that are at high risk of becoming seriously ill from COVID-19 as per CDC’s BRFSS','The number of high risk individuals per ICU bed in that area','The number of high risk individuals per hospital in that area','The number of ICU beds in the area, based on the Kaiser Family Foundation’s data','	The number of hospitals in the area, based on the Kaiser Family Foundation’s data','The total number of high risk individuals in the area, per CDC’s BRFSS')
description_table <- data.frame(names(Coviddata), description)
kable(description_table, "pipe", col.names = NULL)
```




```{r, echo=TRUE}
#Summary of Coloumns choosen are as follows:
#1. patient_per_ICU_bed"
#2 Patient_per_hospital
#3 no_icu
#4 no_hospital
#5 total_at_risk

total_summary <- summarise_each(Coviddata[,c("patient_per_ICU_bed","Patient_per_hospital", "no_icu","no_hospital", "total_at_risk")], funs(mean))

# print summary
total_summary
```

```

